# Generated by Django 5.0.3 on 2024-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_description_ru_category_description_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_adress', models.CharField(max_length=255, verbose_name='Adress')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('work_address', models.CharField(max_length=255, verbose_name='Work Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
