# Generated by Django 5.0.3 on 2024-08-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_urlvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlvideo',
            old_name='url_adress',
            new_name='url_address',
        ),
    ]
